### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by jjromary** [jjromary/top-music-deezerAPI#1]
**Styles**

- [x] Create Theme and Global styles #10 

**Create Components**

- [x] Header component #2 
- [x] Button component  #3
- [x] Card Track component  #4
- [x] Search Bar component  #5
- [x] Play/Pause component  #6

**Routes**

- [x] Create Routes and Default Layout #7 
- [x] Create Layout Page '/favorite' #18 

**Deezer API**

- [x] Connect Deezer API with Axios #9 
- [x] Create ContextApi #21 

**Features**

- [x] Search component functional #23 
- [x] Infinite scroll #8 
- [x]  Favorites List #29 
- [ ] Responsive Layout #28 
- [x] Custom Player #31 
- [x] Data persistence in the favorites list #36

**BUG**

- [x] ERROS CORS #26 

**Refactoring Code**

- [x] ContextAPI #34
